Repository FRONTENDBOOTCAMP-13th/Final-13-13tachi, pull requests merged in 2025-07, with the labels that each got.

#23 Feat/recipe list
  src/app/globals.css
  src/app/recipe/list/RecipeCarousel.tsx
  src/app/recipe/list/RecipeList.tsx
  src/app/recipe/list/page.tsx
Labels: feature

#25 ✨ feat: 레시피 검색결과 페이지 마크업 및 스타일링 완료
  public/imgs/ico-bookmark.png
  public/imgs/left-arrow.png
  public/imgs/recipe/recipe1.png
  public/imgs/recipe/recipe10.png
  public/imgs/recipe/recipe11.png
  public/imgs/recipe/recipe12.png
  public/imgs/recipe/recipe13.png
  public/imgs/recipe/recipe2.png
  public/imgs/recipe/recipe3.png
  public/imgs/recipe/recipe4.png
  public/imgs/recipe/recipe5.png
  public/imgs/recipe/recipe6.png
  public/imgs/recipe/recipe7.png
  public/imgs/recipe/recipe8.png
  public/imgs/recipe/recipe9.png
  public/imgs/recipe/udong.png
  public/imgs/right-arrow.png
  src/app/recipe/search/RecipeSearch.tsx
  src/app/recipe/search/[ingredient]/page.tsx
Labels: feature

#39 ✨ feat: 레시피 등록 페이지 UI
  package-lock.json
  package.json
  public/imgs/toggle.svg
  src/app/recipe/RecipeCarousel.tsx
  src/app/recipe/RecipeList.tsx
  src/app/recipe/detail/page.tsx
  src/app/recipe/page.tsx
  src/app/recipe/search/[ingredient]/page.tsx
  src/app/recipe/write/TextEditor.tsx
  src/app/recipe/write/page.tsx
Labels: feature

#48 ✨ feat: 레시피 작성 페이지 UI
  src/app/recipe/RecipeList.tsx
  src/app/recipe/page.tsx
  src/app/recipe/search/RecipeSearch.tsx
  src/app/recipe/search/[ingredient]/page.tsx
  src/app/recipe/write/page.tsx
  src/components/common/Input.tsx
Labels: feature

#59 Refactor/search
  src/app/recipe/detail/page.tsx
  src/app/recipe/page.tsx
  src/app/recipe/search/RecipeSearch.tsx
  src/app/recipe/search/[ingredient]/page.tsx
  src/components/common/Input.tsx
  src/components/common/Search.tsx
Labels: refactor

#61 ✨ feat: 레시피 글쓰기 페이지 수정
  src/app/recipe/write/page.tsx
Labels: feature

#67 Feat/signup
  package-lock.json
  package.json
  src/app/mypage/user/page.tsx
  src/app/user/login/LoginForm.tsx
  src/app/user/signup/SignupForm.tsx
  src/data/actions/user.ts
Labels: feature

#73 ♻️ refactor: 루시드 아이콘으로 아이콘 이미지 변경
  src/app/recipe/RecipeCarousel.tsx
  src/app/recipe/RecipeList.tsx
  src/app/recipe/page.tsx
  src/app/recipe/search/[ingredient]/page.tsx
  src/app/recipe/write/page.tsx
  src/app/shopping/page.tsx
  src/app/shopping/search/page.tsx
  src/components/common/SearchBar.tsx
Labels: refactor

#78 Feat/post api
  src/app/mypage/user/page.tsx
  src/app/user/edit/EditForm.tsx
  src/app/user/login/LoginForm.tsx
  src/app/user/signup/SignupForm.tsx
  src/components/common/Address.tsx
Labels: feature

#143 ✨ feat: 레시피 댓글 기능 구현
  src/app/recipe/[id]/Comment.tsx
  src/app/recipe/[id]/CommentActionButton.tsx
  src/app/recipe/[id]/Comments.tsx
  src/app/recipe/[id]/page.tsx
Labels: feature

#141 Bug/orderForm
  src/app/order/OrderItemForm.tsx
  src/app/order/OrderList.tsx
  src/app/order/OrderUserForm.tsx
  src/app/order/PayForm.tsx
  src/components/common/Address.tsx
Labels: bug

#147 ♻️ refactor: 레시피 SWAL 변경
  src/app/recipe/[id]/Comment.tsx
  src/app/recipe/[id]/CommentActionButton.tsx
  src/app/recipe/[id]/Comments.tsx
  src/app/recipe/[id]/RecipeActionButton.tsx
  src/app/recipe/[id]/edit/RecipeEditForm.tsx
  src/app/recipe/write/page.tsx
Labels: refactor
